# Generated by Django 4.2.13 on 2024-06-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_project", models.CharField(max_length=200)),
                ("date_project", models.DateTimeField(verbose_name="date published")),
                ("descripton_project", models.CharField(max_length=200)),
                ("endereco_foto", models.CharField(max_length=200)),
            ],
        ),
    ]
