# Generated by Django 4.2.13 on 2024-06-02 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0002_rename_date_project_projetos_data_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projetos",
            old_name="data_project",
            new_name="data_projeto",
        ),
        migrations.RenameField(
            model_name="projetos",
            old_name="descricao_project",
            new_name="descricao_projeto",
        ),
        migrations.RenameField(
            model_name="projetos",
            old_name="nome_project",
            new_name="nome_projeto",
        ),
    ]
