# Generated by Django 4.2.13 on 2024-06-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0003_rename_data_project_projetos_data_projeto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projetos",
            name="data_projeto",
            field=models.DateTimeField(verbose_name="Data do Projeto"),
        ),
        migrations.AlterField(
            model_name="projetos",
            name="foto_projeto",
            field=models.ImageField(upload_to=""),
        ),
    ]
